if vim.g.use_lsp then
  require('cko.lsp')
else
  require('cko.coc')
end

require('cko.airline')
require('cko.dadbod')
require('cko.doge')
require('cko.dotoo')
require('cko.easymotion')
require('cko.emmet')
require('cko.fzf')
require('cko.indent-line')
require('cko.nvim-colorizer')
require('cko.nvim-compe')
require('cko.nvim-tree')
require('cko.nvim-web-devicons')
require('cko.rooter')
require('cko.startify')
require('cko.telescope')
require('cko.tree-sitter')
require('cko.undo-tree')
require('cko.vim-go')
require('cko.vimlsp')
require('cko.vimspector')
require('cko.vimspector')
